# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class NanoAgent < Formula
  desc "Nano Agent — image generation and critique CLI for Gemini"
  homepage "https://github.com/rkirkendall/nano-agent"
  version "0.1.10"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/rkirkendall/nano-agent/releases/download/v0.1.10/nano-agent_darwin_amd64.tar.gz"
      sha256 "bc7434c8c393c24ba89e0d5d124ff0b8f7aa0deed3a5e1441b5386aaa6ab54d3"

      def install
        bin.install "nano-agent"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/rkirkendall/nano-agent/releases/download/v0.1.10/nano-agent_darwin_arm64.tar.gz"
      sha256 "adfc0e0eaa0dd4924bb6e08bc50352c40b8b7f23c819ebf9420da3c6e8fb628f"

      def install
        bin.install "nano-agent"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? and Hardware::CPU.is_64_bit?
      url "https://github.com/rkirkendall/nano-agent/releases/download/v0.1.10/nano-agent_linux_amd64.tar.gz"
      sha256 "161c32f0c952ab5997b8247e6fcde588d2d786ffe4d675c32ee6ad0ab0de5773"
      def install
        bin.install "nano-agent"
      end
    end
    if Hardware::CPU.arm? and Hardware::CPU.is_64_bit?
      url "https://github.com/rkirkendall/nano-agent/releases/download/v0.1.10/nano-agent_linux_arm64.tar.gz"
      sha256 "869fc6b3db2715b5e12e05e1e0bc0bf1f8e6ac4c5c6b2df05e51985961f29dc1"
      def install
        bin.install "nano-agent"
      end
    end
  end
end
