# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class NanoAgent < Formula
  desc "Nano Agent — image generation and critique CLI for Gemini"
  homepage "https://github.com/rkirkendall/nano-agent"
  version "0.1.9"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/rkirkendall/nano-agent/releases/download/v0.1.9/nano-agent_darwin_amd64.tar.gz"
      sha256 "0102078118b1d58ba41a7281326203911ca66684f80df9f25b2ba3470e72d616"

      def install
        bin.install "nano-agent"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/rkirkendall/nano-agent/releases/download/v0.1.9/nano-agent_darwin_arm64.tar.gz"
      sha256 "35338cfe723ac6ba41dfae6172a0ddaa712aa22156ab859fcd74c6e67677762e"

      def install
        bin.install "nano-agent"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? and Hardware::CPU.is_64_bit?
      url "https://github.com/rkirkendall/nano-agent/releases/download/v0.1.9/nano-agent_linux_amd64.tar.gz"
      sha256 "e8b3c68f8ef1e24382eb57553418abeee9beb0d9543d26d684cbb282211bed51"
      def install
        bin.install "nano-agent"
      end
    end
    if Hardware::CPU.arm? and Hardware::CPU.is_64_bit?
      url "https://github.com/rkirkendall/nano-agent/releases/download/v0.1.9/nano-agent_linux_arm64.tar.gz"
      sha256 "5752bb0244478dc003cca73046ed032e3fb0b7fc98306e8b96dd6d2172e78b14"
      def install
        bin.install "nano-agent"
      end
    end
  end
end
